### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by rachelleahklein** [newrelic/newrelic-telemetry-sdk-ruby#11]
Make sure we are [logging](https://github.com/newrelic/newrelic-telemetry-sdk-specs/blob/master/configuration-and-logging.md#logging) appropriately per the specs.

**Comment by mwlang** [comment]
We needed logging functionality for handling client/server responses, so this issue started and is part of #27.  The PR doesn't necessarily implement all logging needs, but does lay the groundwork for resolving this issue/effort.

**Comment by rachelleahklein** [comment]
@mwlang Since we've been adding log messages ad-hoc, my proposed final task was just to scan the whole codebase once more to see if there are any remaining situations in which logs would be helpful.

**Comment by rachelleahklein** [comment]
One thing we definitely still need to add, per the spec, is highly verbose debug/audit logging (e.g. logging the entire contents of each payload sent when audit logging is enabled).

**Comment by rachelleahklein** [comment]
Outstanding logging needs have been addressed in #32.
