### ISSUE TITLE
Intermittent unit test failure

### ISSUE THREAD

**Issue by mwlang** [newrelic/newrelic-telemetry-sdk-ruby#31]
## Description

When running unit tests, I see an intermittent test failure about 1 in 3 runs:

```
Failure:
NewRelic::TelemetrySdk::SpanTest#test_finish_with_end_time_supplied [/Users/mlang/projects/telemetry/sdk/test/new_relic/telemetry_sdk/span_test.rb:82]:
Expected: 1000
  Actual: 1001
```

## Steps to Reproduce

`rake test`

**Comment by rachelleahklein** [comment]
Sad to see this! We had hoped it was fixed by #25.

**Comment by mwlang** [comment]
I just looked at this a little more deeply.  It's a rounding error and perhaps a design flaw exposed as well.

The math we are currently employing for computing durations is doing so with an integral representation in milliseconds.

```ruby
 def finish end_time_ms: Util.time_to_ms
   @duration_ms = end_time_ms - @start_time_ms
 end
```
If the math were, instead, using floats, then we would avoid the rounding error.  Consider:

```ruby
start = Time.now; t.to_f * 1000; 
finish = start + 1; 
delta = (finish - start).to_f * 1000
puts delta
=> 1000.0
```
This will always return `1000.0` and thus round to `1000` milliseconds.

**Comment by mwlang** [comment]
PR #32 resolves this bug.
