### ISSUE TITLE
Add Ruby to list of languages with SDK's published.

### ISSUE THREAD

**Issue by mwlang** [newrelic/newrelic-telemetry-sdk-ruby#34]
We need to add Ruby to the SDK Specs README when we release:

https://github.com/newrelic/newrelic-telemetry-sdk-specs

**Comment by mwlang** [comment]
https://github.com/newrelic/newrelic-telemetry-sdk-specs/pull/24 resolves this issue when it's approved and merged.

**Comment by rachelleahklein** [comment]
It's now been approved and merged!
