### ISSUE TITLE
Update New Relic documentation to add ruby telemetry sdk

### ISSUE THREAD

**Issue by tannalynn** [newrelic/newrelic-telemetry-sdk-ruby#39]
Update documentation [here](https://docs.newrelic.com/docs/telemetry-data-platform/get-started/capabilities/telemetry-sdks-send-custom-telemetry-data-new-relic) to add ruby to the list of available libraries with a link to the repo, and traces listed as being supported.

**Comment by rachelleahklein** [comment]
Submitted draft to docs team today.

**Comment by rachelleahklein** [comment]
Approved for publication.
